/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaswingdev.form;

import controller.ChiTietHoaDonController;
import controller.HoaDonController;
import controller.KhachHangController;
import controller.KhuyenMaiController;
import controller.SanPhamController;
import controller.TaiKhoanNhanVienController;
import java.util.List;
import static javaswingdev.form.DangNhap.Ma_NhanVienstatic;
import static javaswingdev.main.MainTaoFrom.taiKhoanNhanVienControllerStatic;
import javax.swing.table.DefaultTableModel;
import model.ChiTietHoaDonModel;
import model.HoaDonModel;
import model.KhachHangModel;
import model.SanPhamModel;
import model.TaiKhoanNhanVIenFull;
import utilities.MsgBox;

/**
 *
 * @author Nong_Tien_Son
 */
public class BanHang extends javax.swing.JPanel {

    private TaiKhoanNhanVIenFull tknvif = taiKhoanNhanVienControllerStatic.selectNhanVienFull(Ma_NhanVienstatic).get(0);
    DefaultTableModel defaultTableModel = new DefaultTableModel();

    KhachHangController khachHangController = new KhachHangController();
    SanPhamController sanPhamController = new SanPhamController();
    KhuyenMaiController khuyenMaiController = new KhuyenMaiController();
    HoaDonController hoaDonController = new HoaDonController();
    TaiKhoanNhanVienController taiKhoanNhanVienController = new TaiKhoanNhanVienController();
    ChiTietHoaDonController chiTietHoaDonController = new ChiTietHoaDonController();

    List<SanPhamModel> listSanPham = sanPhamController.getAllSanPhamChiTiet();
    List<HoaDonModel> listHoaDonTreo = hoaDonController.timKiemTatCaHoaTreo();
    List<HoaDonModel> listHoaDonDaTao = hoaDonController.timKiemTatCaHoaDon();
    List<KhachHangModel> listKhachHang = khachHangController.timKiemTatCaKhachHang();
    List<ChiTietHoaDonModel> listChiTietHoaDon = chiTietHoaDonController.timtatCatChiTietHoaDon();
    List<ChiTietHoaDonModel> listHoaDonChiTietTheoMa = null;

    /**
     * Creates new form BanHang
     */
    public BanHang() {
        initComponents();
        hienThiBangSanPhamCuaHang();
        hienThiLenHoaDonTreo();
    }

    private void hienThiLenHoaDonTreo() {
        defaultTableModel = (DefaultTableModel) tblHoaDonTreo.getModel();
        defaultTableModel.setRowCount(0);

        for (HoaDonModel hoaDonModel : listHoaDonTreo) {
            defaultTableModel.addRow(new Object[]{
                hoaDonModel.getMaHoaDon()
            });
        }
    }

    private void hienThiTableDonHangChiTiet() {
        defaultTableModel = (DefaultTableModel) tblDonHangChiTiet.getModel();
        defaultTableModel.setRowCount(0);
        listHoaDonChiTietTheoMa = chiTietHoaDonController.timtatCatChiTietHoaDonTheoMa(tblHoaDonTreo.getValueAt(tblHoaDonTreo.getSelectedRow(), 0).toString());
        int tongTien = 0;

        for (ChiTietHoaDonModel chiTietHoaDonModel : listHoaDonChiTietTheoMa) {
            defaultTableModel.addRow(new Object[]{
                chiTietHoaDonModel.getMaSanPhamChiTiet(),
                chiTietHoaDonModel.getTenSanPham(),
                chiTietHoaDonModel.getDonGia(),
                chiTietHoaDonModel.getSoLuong(),
                chiTietHoaDonModel.getTongTien()
            });
            tongTien+=chiTietHoaDonModel.getTongTien();
            txtTongTien.setText(String.valueOf(tongTien));
        }
        int giaTriMaGiamGia = khuyenMaiController.timKiemKhuyenMaitheoMa(txtMaGiamGia.getText()).get(0).getGiaTri();
        System.out.println(giaTriMaGiamGia);
        txtGiaTriGiamGia.setText(String.valueOf(tinhTienSauGiamGia(tongTien, giaTriMaGiamGia))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        roundPanel1 = new javaswingdev.swing.RoundPanel();
        roundPanel2 = new javaswingdev.swing.RoundPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPhamCuaHang = new javaswingdev.swing.table.Table();
        roundPanel7 = new javaswingdev.swing.RoundPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        roundPanel3 = new javaswingdev.swing.RoundPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDonHangChiTiet = new javaswingdev.swing.table.Table();
        roundPanel4 = new javaswingdev.swing.RoundPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        txtSoDienThoaiKhachHang = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSoDienThoaiNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        txtSoTienKhachDua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaGiamGia = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtSoTienConThieu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtGiaTriGiamGia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        roundPanel5 = new javaswingdev.swing.RoundPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDonTreo = new javaswingdev.swing.table.Table();

        roundPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SẢN PHẨM"));

        tblSanPhamCuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Kho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSanPhamCuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamCuaHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPhamCuaHang);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel7Layout = new javax.swing.GroupLayout(roundPanel7);
        roundPanel7.setLayout(roundPanel7Layout);
        roundPanel7Layout.setHorizontalGroup(
            roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel7Layout.createSequentialGroup()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roundPanel7Layout.setVerticalGroup(
            roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        roundPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("ĐƠN HÀNG"));

        tblDonHangChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá", "Số lượng", "Tổng tiền"
            }
        ));
        tblDonHangChiTiet.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblDonHangChiTietAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblDonHangChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonHangChiTietMouseClicked(evt);
            }
        });
        tblDonHangChiTiet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblDonHangChiTietKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblDonHangChiTiet);

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn chi tiết"));

        jLabel1.setText("Mã hóa đơn ");

        txtMaHoaDon.setEnabled(false);

        jToggleButton1.setText("NEW");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("SDT khách hàng");

        txtSoDienThoaiKhachHang.setEnabled(false);

        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ADD");

        jLabel3.setText("SDT nhân viên");

        txtSoDienThoaiNV.setEnabled(false);

        jLabel4.setText("Tổng tiền");

        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        txtSoTienKhachDua.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSoTienKhachDuaPropertyChange(evt);
            }
        });

        jLabel5.setText("Số tiền khách đưa");

        jLabel6.setText("Mã giảm giá");

        txtMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGiamGiaActionPerformed(evt);
            }
        });

        jButton3.setText("FIND");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Số tiền còn thiếu");

        jButton5.setText("Hủy");

        jButton6.setText("Thanh toán");

        jButton7.setText("In hóa đơn");

        jButton8.setText("Tạo mã qr");

        txtSoTienConThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoTienConThieuActionPerformed(evt);
            }
        });

        jLabel8.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane4.setViewportView(txtGhiChu);

        jButton9.setText("Lưu");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Số tiền được giảm");

        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(txtMaHoaDon)
                            .addComponent(txtSoDienThoaiKhachHang)
                            .addComponent(txtSoDienThoaiNV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel4Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(roundPanel4Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(6, 6, 6))))
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(roundPanel4Layout.createSequentialGroup()
                                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundPanel4Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jButton5))
                                    .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundPanel4Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8))
                                    .addGroup(roundPanel4Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(txtGiaTriGiamGia)
                                        .addGap(118, 118, 118))
                                    .addGroup(roundPanel4Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTongTien)
                                            .addComponent(txtMaGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                            .addGroup(roundPanel4Layout.createSequentialGroup()
                                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoTienKhachDua)
                                    .addComponent(txtSoTienConThieu, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jLabel4))
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoDienThoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoDienThoaiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel4Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6))
                            .addComponent(txtMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGiaTriGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoTienConThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton9)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(349, Short.MAX_VALUE))
        );

        roundPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn treo"));

        tblHoaDonTreo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        tblHoaDonTreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonTreoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHoaDonTreo);

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, Short.MAX_VALUE)
                    .addComponent(roundPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(roundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(512, 512, 512))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoaDonTreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonTreoMouseClicked
        hienThiHoaDonTreo();
    }//GEN-LAST:event_tblHoaDonTreoMouseClicked

    private void hienThiHoaDonTreo() {
        // TODO add your handling code here:
        int dongDuocChon = tblHoaDonTreo.getSelectedRow();
        
        
        
        
        if (dongDuocChon > -1) {
            HoaDonModel donModel = listHoaDonTreo.get(dongDuocChon);
            txtMaHoaDon.setText(donModel.getMaHoaDon());
            txtSoDienThoaiKhachHang.setText(donModel.getSoDienThoaiKH());
            txtSoDienThoaiNV.setText(donModel.getSoDienThoaiNV());
            txtGhiChu.setText(donModel.getGhiChu());
            txtMaGiamGia.setText(donModel.getMaKhuyenMai());
            txtTongTien.setText(String.valueOf(donModel.getTongTien()));
            hienThiTableDonHangChiTiet();
        }
    }
    
    private void txtSoTienConThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoTienConThieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoTienConThieuActionPerformed

    private void txtMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGiamGiaActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int soHoaDon = 0;
        try {
            soHoaDon = listHoaDonDaTao.size();
            soHoaDon = listHoaDonTreo.size() + soHoaDon;

            HoaDonModel hoaDonMoi = new HoaDonModel();
            hoaDonMoi.setMaHoaDon("HD" + soHoaDon);
            hoaDonMoi.setSoDienThoaiKH(listKhachHang.get(0).getSoDienThoai());
            hoaDonMoi.setSoDienThoaiNV(tknvif.getSoDienThoai());
            java.time.LocalDate ngayHomNay = java.time.LocalDate.now();
            hoaDonMoi.setNgaySua(java.sql.Date.valueOf(ngayHomNay));
            hoaDonMoi.setNgayTao(java.sql.Date.valueOf(ngayHomNay));
            hoaDonMoi.setTrangThai(true);

            hoaDonController.themHoaDonMoi(hoaDonMoi);

            listHoaDonTreo = hoaDonController.timKiemTatCaHoaTreo();
            hienThiLenHoaDonTreo();
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void tblDonHangChiTietKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDonHangChiTietKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDonHangChiTietKeyPressed

    private void tblDonHangChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangChiTietMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDonHangChiTietMouseClicked

    private void tblDonHangChiTietAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblDonHangChiTietAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDonHangChiTietAncestorAdded

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if (txtTimKiem.getText().trim().equals("")) {
            MsgBox.alert(this, "Bạn cần nhập mã hoặc tên sản phẩm cần tìm");
            listSanPham = sanPhamController.getAllSanPhamChiTiet();
            hienThiBangSanPhamCuaHang();
        } else {
            listSanPham = sanPhamController.timSanPhamChiTietGanDung(txtTimKiem.getText());
            hienThiBangSanPhamCuaHang();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblSanPhamCuaHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamCuaHangMouseClicked
        // TODO add your handling code here:
        try {
            int indexSanPhamMuonThem = tblSanPhamCuaHang.getSelectedRow();

            if (txtMaHoaDon.getText().trim().equals("")) {
                MsgBox.alert(this, "Bạn cần phải tạo hóa đơn hoặc chọn hóa đơn trước khi thêm sản phẩm vào hóa đơn !");
                return;
            }

            try {
                int soLuong = Integer.valueOf(MsgBox.promt(this, "Mời nhập bạn nhập số lượng hàng"));
                listChiTietHoaDon = chiTietHoaDonController.timtatCatChiTietHoaDon();
                int tongTien = soLuong *(int) tblSanPhamCuaHang.getValueAt(indexSanPhamMuonThem, 2);
                System.out.println(tongTien);
                ChiTietHoaDonModel chiTietHoaDonModel = new ChiTietHoaDonModel(
                        "HD" + listChiTietHoaDon.size() + 1,
                        txtMaHoaDon.getText(),
                         (String) tblSanPhamCuaHang.getValueAt(indexSanPhamMuonThem, 0),
                         (String) tblSanPhamCuaHang.getValueAt(indexSanPhamMuonThem, 1),
                        soLuong,
                        (int) tblSanPhamCuaHang.getValueAt(indexSanPhamMuonThem, 2),
                        tongTien);

                boolean ketQua = chiTietHoaDonController.themHoaDonChiTiet(chiTietHoaDonModel);
                if (ketQua) {
                    hienThiHoaDonTreo();
                } else {
                    MsgBox.alert(this, "Đã có lỗi khi thêm sản phẩm");
                }
            } catch (NumberFormatException numberFormatException) {
                MsgBox.alert(this, "Bạn cần nhập số lượng là số");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Bạn cần tạo hóa đơn trước khi thêm sản phẩm vào");
        }
    }//GEN-LAST:event_tblSanPhamCuaHangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String soDienThoaiKH = MsgBox.promt(this, "Mời bạn nhập số điện thoại khách hàng");

        try {
            KhachHangModel khachHangModel = khachHangController.timKiemKhachHangTheoSDT(soDienThoaiKH).get(0);
            txtSoDienThoaiKhachHang.setText(khachHangModel.getSoDienThoai());
        } catch (Exception e) {
            MsgBox.alert(this, "Không tìm thấy khách hàng");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSoTienKhachDuaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSoTienKhachDuaPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSoTienKhachDuaPropertyChange

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        if (txtTongTien.getText().trim().equals("")) {

        } else {
            int tongTien = Integer.parseInt(txtTongTien.getText());
            int soTienKhachDua = Integer.parseInt(txtSoTienKhachDua.getText());
            int soTienPhaiTraKhach = soTienKhachDua - tongTien;
            txtSoTienConThieu.setText(String.valueOf(soTienPhaiTraKhach));
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (true) {
            int ketQua = hoaDonController.capNhatHoaDonTreo(layGiaTriHoaDon());
            if (ketQua > 0) {
                MsgBox.alert(this, "Cập nhật hóa đơn" + layGiaTriHoaDon().getMaHoaDon() + " thành công");
                listHoaDonTreo = hoaDonController.timKiemTatCaHoaTreo();
                hienThiLenHoaDonTreo();
            } else {
                MsgBox.alert(this, "Cập nhật hóa đơn" + layGiaTriHoaDon().getMaHoaDon() + " thất bại có thể vì hóa đơn không tồn tại");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int tongTien = 0;
        for (ChiTietHoaDonModel chiTietHoaDonModel : listChiTietHoaDon) {
//            chiTietHoaDonModel.get
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private HoaDonModel layGiaTriHoaDon() {
        HoaDonModel hoaDonModel = new HoaDonModel();
        hoaDonModel.setMaHoaDon(txtMaHoaDon.getText());
        hoaDonModel.setSoDienThoaiKH(txtSoDienThoaiKhachHang.getText());
        hoaDonModel.setSoDienThoaiNV(txtSoDienThoaiNV.getText());
        hoaDonModel.setGhiChu(txtGhiChu.getText());
        hoaDonModel.setMaKhuyenMai(txtMaGiamGia.getText());
        hoaDonModel.setTongTien(Integer.parseInt(txtTongTien.getText()));
        return hoaDonModel;
    }

    private void hienThiBangSanPhamCuaHang() {
        defaultTableModel = (DefaultTableModel) tblSanPhamCuaHang.getModel();
        defaultTableModel.setRowCount(0);
        for (SanPhamModel sanPhamModel : listSanPham) {
            defaultTableModel.addRow(new Object[]{
                sanPhamModel.getMa_SanPhamChiTiet(),
                sanPhamModel.getTen(),
                sanPhamModel.getGiaBan(),
                sanPhamModel.getSoLuong()
            });
        }
    }

    private void hienThiBangSanPhamDonHang() {

    }

    private int tinhTienSauGiamGia(int tongTien, int giaTriMaGiamGia) {
        int giaTienSauGiamGia = 0;
        if (giaTriMaGiamGia <= 100 && giaTriMaGiamGia >= 1) {
            giaTienSauGiamGia = (tongTien/100)*giaTriMaGiamGia;
        } else {
            giaTienSauGiamGia = tongTien-giaTriMaGiamGia;
        }

        return giaTienSauGiamGia < 0 ? 0 : giaTienSauGiamGia;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javaswingdev.swing.RoundPanel roundPanel1;
    private javaswingdev.swing.RoundPanel roundPanel2;
    private javaswingdev.swing.RoundPanel roundPanel3;
    private javaswingdev.swing.RoundPanel roundPanel4;
    private javaswingdev.swing.RoundPanel roundPanel5;
    private javaswingdev.swing.RoundPanel roundPanel7;
    private javaswingdev.swing.table.Table tblDonHangChiTiet;
    private javaswingdev.swing.table.Table tblHoaDonTreo;
    private javaswingdev.swing.table.Table tblSanPhamCuaHang;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGiaTriGiamGia;
    private javax.swing.JTextField txtMaGiamGia;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtSoDienThoaiKhachHang;
    private javax.swing.JTextField txtSoDienThoaiNV;
    private javax.swing.JTextField txtSoTienConThieu;
    private javax.swing.JTextField txtSoTienKhachDua;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
