/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaswingdev.form;

import controller.KhuyenMaiController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.KhuyenMai;
import utilities.MsgBox;

/**
 *
 * @author Khanh
 */
public class FormKhuyenMai extends javax.swing.JPanel {
    KhuyenMaiController khuyenMaiController = new KhuyenMaiController();
    List<KhuyenMai> danhSachkhuyenmai =  khuyenMaiController.timKiemTatCaKuyenMai();
    /**
     * Creates new form FormKhuyenMai
     */
    public FormKhuyenMai() {
        initComponents();
        loadFormKhuyenMai();
    }
    private void loadFormKhuyenMai(){
        DefaultTableModel dtm = (DefaultTableModel) tblBangkhuyenmai.getModel();
        dtm.setRowCount(0);
        
        for (KhuyenMai khyenMai : danhSachkhuyenmai) {
            dtm.addRow(new Object[]{
                khyenMai.getMaKhuyenMai(),
                khyenMai.getTenKhuyenMai(),
                khyenMai.getGiaTri(),
                khyenMai.isLoaiKhuyenMai()?"Tiền mặt" : "Phần trăm",
                khyenMai.getNgayBatDau(),
                khyenMai.getNgayKetThuc(),
                khyenMai.isTrangThai()?"Còn khuyến mại" : "Hết khuyến mại"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMakhuyenmai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenkhuyenmai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGiaTri = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdoTienmat = new javax.swing.JRadioButton();
        rdoPhantram = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtNgaybatdau = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtNgayketthuc = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        rdoConkhuyenmai = new javax.swing.JRadioButton();
        rdoHetkhuyenmai = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtTimkhuyenmai = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangkhuyenmai = new javaswingdev.swing.table.Table();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Khuyến Mãi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel2.setText("Mã khuyến mãi");

        jLabel3.setText("Tên khuyến mãi");

        jLabel4.setText("Giá trị");

        jLabel5.setText("Loại khuyến mãi");

        buttonGroup1.add(rdoTienmat);
        rdoTienmat.setText("Tiền mặt");

        buttonGroup1.add(rdoPhantram);
        rdoPhantram.setText("Phần trăm");

        jLabel6.setText("Ngày bắt đầu");

        jLabel7.setText("Ngày kết thúc");

        jLabel8.setText("Trạng thái");

        buttonGroup2.add(rdoConkhuyenmai);
        rdoConkhuyenmai.setText("Còn khuyến mãi");

        buttonGroup2.add(rdoHetkhuyenmai);
        rdoHetkhuyenmai.setText("Hết khuyến mãi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoConkhuyenmai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoHetkhuyenmai))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMakhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgaybatdau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(rdoTienmat)
                                .addGap(45, 45, 45)
                                .addComponent(rdoPhantram))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtTenkhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMakhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenkhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoTienmat)
                    .addComponent(rdoPhantram))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgaybatdau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtNgayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoConkhuyenmai)
                    .addComponent(rdoHetkhuyenmai))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addGap(43, 43, 43)
                .addComponent(btnLammoi)
                .addGap(71, 71, 71)
                .addComponent(txtTimkhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTim)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(txtTimkhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(btnLammoi))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tblBangkhuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mại", "Tên khuyến mại", "Giá trị", "Loại khuến mại", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ));
        tblBangkhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangkhuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBangkhuyenmai);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblBangkhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangkhuyenmaiMouseClicked
        // TODO add your handling code here:
        if(tblBangkhuyenmai.getSelectedRow() > -1){
            KhuyenMai khuyenMai = khuyenMaiController.timKiemTatCaKuyenMai().get(tblBangkhuyenmai.getSelectedRow());
       txtMakhuyenmai.setText(khuyenMai.getMaKhuyenMai());
       txtTenkhuyenmai.setText(khuyenMai.getTenKhuyenMai());
       txtGiaTri.setText(String.valueOf(khuyenMai.getGiaTri()));
       txtNgaybatdau.setDate(khuyenMai.getNgayBatDau());
       txtNgayketthuc.setDate(khuyenMai.getNgayKetThuc());
       if(khuyenMai.isLoaiKhuyenMai()){
           rdoPhantram.setSelected(true);
       }else{
           rdoTienmat.setSelected(true);
       }
       if(khuyenMai.isTrangThai()){
           rdoConkhuyenmai.setSelected(true);
       }else{
           rdoHetkhuyenmai.setSelected(true);
       }
        }
    }//GEN-LAST:event_tblBangkhuyenmaiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(checktrong()){
            boolean ketqua = khuyenMaiController.themKhuyenMai(taodulieumoi());
            if(ketqua){
                MsgBox.alert(this, "Bạn đã thêm khuyến mãi thành công");
                loadFormKhuyenMai();
            }else{
                MsgBox.alert(this, "Bạn đã thêm khuyến mãi thất bại");
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(tblBangkhuyenmai.getSelectedRow()>-1){
            boolean luachon = MsgBox.confirm(this, "Bạn có muốn sửa không");
            if(luachon){
                boolean ketqua = khuyenMaiController.capNhatThongTinKhuyenMai(taodulieumoi());
                if(ketqua){
                    MsgBox.alert(this, "Bạn đã sửa thành công");
                    danhSachkhuyenmai = khuyenMaiController.timKiemTatCaKuyenMai();
                    loadFormKhuyenMai();
                }else{
                    MsgBox.alert(this, "Bạn đã sửa không thành công");
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if(txtTimkhuyenmai.getText().trim().equals("")){
            
        }else{
            danhSachkhuyenmai = khuyenMaiController.timKiemKhuyenMaitheoMa(txtTimkhuyenmai.getText());
            loadFormKhuyenMai();
        }
    }//GEN-LAST:event_btnTimActionPerformed
private void lamMoiTextField(){
    txtGiaTri.setText("");
    txtMakhuyenmai.setText("");
    txtTenkhuyenmai.setText("");
    java.time.LocalDate ngaySuaLocalDate = java.time.LocalDate.now();
        txtNgaybatdau.setDate(java.sql.Date.valueOf(ngaySuaLocalDate));
        txtNgayketthuc.setDate(java.sql.Date.valueOf(ngaySuaLocalDate));
}
    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        lamMoiTextField();
        
    }//GEN-LAST:event_btnLammoiActionPerformed
private KhuyenMai taodulieumoi(){
    KhuyenMai khuyenMai = new KhuyenMai();
    khuyenMai.setMaKhuyenMai(txtMakhuyenmai.getText());
    khuyenMai.setTenKhuyenMai(txtTenkhuyenmai.getText());
    khuyenMai.setGiaTri(Integer.valueOf(txtGiaTri.getText()));
    khuyenMai.setLoaiKhuyenMai(rdoPhantram.isSelected());
    khuyenMai.setTrangThai(rdoConkhuyenmai.isSelected());
    java.util.Date utilDate = txtNgaybatdau.getCalendar().getTime(); // Lấy đối tượng java.util.Date
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime()); // Chuyển đổi sang java.sql.Date
        khuyenMai.setNgayBatDau(sqlDate);
    
        java.util.Date utilDatee = txtNgayketthuc.getCalendar().getTime(); // Lấy đối tượng java.util.Date
        java.sql.Date sqlDatee = new java.sql.Date(utilDate.getTime()); // Chuyển đổi sang java.sql.Date
        khuyenMai.setNgayKetThuc(sqlDate);
        
        return khuyenMai;
}
public Boolean checktrong(){
    if (txtMakhuyenmai.getText().trim().equals("")) {
            MsgBox.alert(this, "Bạn cần nhập Mã khuyến mại");
            return false;
        }
        if (txtTenkhuyenmai.getText().trim().equals("")) {
            MsgBox.alert(this, "Bạn cần nhập Tên khách hàng");
            return false;
        }
        if (txtGiaTri.getText().trim().equals("")) {
            MsgBox.alert(this, "Bạn cần nhập giá trị");
            return false;
        }
        if(rdoConkhuyenmai.isSelected()==false && rdoHetkhuyenmai.isSelected()==false){
            MsgBox.alert(this, "Bạn cần nhập trạng thái");
            return false;
        }
        if(rdoPhantram.isSelected()==false && rdoTienmat.isSelected()==false){
            MsgBox.alert(this, "Bạn cần nhập loại khyến mại");
            return false;
        }
       try {
        java.util.Date utilDate = txtNgaybatdau.getCalendar().getTime(); // Lấy đối tượng java.util.Date
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime()); // Chuyển đổi sang java.sql.Date
       
    } catch (Exception e) {
        MsgBox.alert(this, "Bạn cần nhập ngày bắt đầu");
            return false;
    }
       try {
        java.util.Date utilDate = txtNgayketthuc.getCalendar().getTime(); // Lấy đối tượng java.util.Date
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime()); // Chuyển đổi sang java.sql.Date
       
    } catch (Exception e) {
        MsgBox.alert(this, "Bạn cần nhập ngày kết thúc");
            return false;
    }
        return true;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoConkhuyenmai;
    private javax.swing.JRadioButton rdoHetkhuyenmai;
    private javax.swing.JRadioButton rdoPhantram;
    private javax.swing.JRadioButton rdoTienmat;
    private javaswingdev.swing.table.Table tblBangkhuyenmai;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtMakhuyenmai;
    private com.toedter.calendar.JDateChooser txtNgaybatdau;
    private com.toedter.calendar.JDateChooser txtNgayketthuc;
    private javax.swing.JTextField txtTenkhuyenmai;
    private javax.swing.JTextField txtTimkhuyenmai;
    // End of variables declaration//GEN-END:variables
}
